### ISSUE TITLE
DNA: remove non-connected components

### ISSUE THREAD

**Issue by TobiasKletter** [tischi/spindle3d#12] opened 2020-11-09 12:39 UTC
In quite a few cases this happens:
Although clearly separate, some adjacent nuclei are incorporated into the DNA mask, messing up downstream analysis steps:

![Screenshot 2020-11-09 at 13 07 36](https://user-images.githubusercontent.com/45814595/98540027-90341e80-228d-11eb-9b32-4f2ee62c26e8.png)
https://www.dropbox.com/s/ttc88wh2m1c0s5i/20201102_R1E309_TubGFP_CKAP51_D2_001-3.tif?dl=0 

![image](https://user-images.githubusercontent.com/45814595/98540654-924aad00-228e-11eb-8e17-be4adffa2643.png)
https://www.dropbox.com/s/zcthbxsa8vnme1o/20201102_R1E309_TubGFP_KATNA1_D4_031-2.tif?dl=0 

I imagine this could be due to the crude initial DNA segmentation, where these objects might end up linked, while afterwards the Otsu-based thresholding separates them again?

(Potentially linked to #11)

**Comment by tischi** [comment] 2020-12-17 10:07
There is another bright object, throwing off the initial threshold computation:

![image](https://user-images.githubusercontent.com/2157566/102473659-04659d00-4058-11eb-8783-a7d7af27fbc2.png)

**Comment by tischi** [comment] 2021-01-08 18:02
closing this as it is a duplicate of other issues.

**Closed by tischi** 2021-01-08 18:02 UTC
